#!/bin/bash -l
#SBATCH -A uppmax2024-2-7
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:10:00
#SBATCH -J quast_001
#SBATCH -e error_quast
#SBATCH --mail-type=ALL
#SBATCH --mail-user emblap@hotmail.se
#SBATCH --output=quast.out
#SBATCH --reservation=uppmax2024-2-7_4

# Load modules
module load bioinfo-tools
module load quast/5.0.2

# Commands
quast.py /home/embla/Genome-analysis-proj2/analysis_output/bwa_pilon/bwa_pilon.fasta \
-r /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/reference_genome/HP126_genome.fasta \
-o /home/embla/Genome-analysis-proj2/analysis_output/quast_mummerplot
