#!/bin/bash -l
#SBATCH -A uppmax2024-2-7
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:30:00
#SBATCH -J fastqc_rna_001
#SBATCH -e error_fastqc_rna
#SBATCH --mail-type=ALL
#SBATCH --mail-user emblap@hotmail.se
#SBATCH --output=fastqc_rna.out
#SBATCH --reservation=uppmax2024-2-7_4

# Load modules
module load bioinfo-tools
module load FastQC/0.11.9

# commands
fastqc /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/RNA_reads/SRR24516459_1.fastq.gz -o /home/embla/Genome-analysis-proj2/anlysis_output/rna_mapping
fastqc /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/RNA_reads/SRR24516459_2.fastq.gz -o /home/embla/Genome-analysis_output/rna_mapping
fastqc /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/RNA_reads/SRR24516460_1.fastq.gz -o /home/embla/Genome-analysis-proj2/analysis_output/rna_mapping
fastqc /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/RNA_reads/SRR24516460_2.fastq.gz -o /home/embla/Genome-analysis-proj2/analysis_output/rna_mapping
fastqc /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/RNA_reads/SRR24516461_1.fastq.gz -o /home/embla/Genome-analysis-proj2/analysis_output/rna_mapping
fastqc /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/RNA_reads/SRR24516461_2.fastq.gz -o /home/embla/Genome-analysis-proj2/analysis_output/rna_mapping
fastqc /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/RNA_reads/SRR24516462_1.fastq.gz -o /home/embla/Genome-analysis-proj2/analysis_output/rna_mapping
fastqc /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/RNA_reads/SRR24516462_2.fastq.gz -o /home/embla/Genome-analysis-proj2/analysis_output/rna_mapping
fastqc /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/RNA_reads/SRR24516463_1.fastq.gz -o /home/embla/Genome-analysis-proj2/analysis_output/rna_mapping
fastqc /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/RNA_reads/SRR24516463_2.fastq.gz -o /home/embla/Genome-analysis-proj2/analysis_output/rna_mapping
fastqc /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/RNA_reads/SRR24516464_1.fastq.gz -o /home/embla/Genome-analysis-proj2/analysis_output/rna_mapping
fastqc /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/RNA_reads/SRR24516464_2.fastq.gz -o /home/embla/Genome-analysis-proj2/analysis_output/rna_mapping
