#!/bin/bash -l
#SBATCH -A uppmax2024-2-7
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 04:00:00
#SBATCH -J flye_001
#SBATCH -e error_flye
#SBATCH --mail-type=ALL
#SBATCH --mail-user emblap@hotmail.se
#SBATCH --output=flye_001.out

# Load modules
module load bioinfo-tools
module load Flye/2.9.1

# Commands
flye --nano-raw ../../rawdata/2_Beganovic_2023/DNA_reads/SRR24413066.fastq.gz --out-dir /home/embla/Genome-analysis-proj2/analysis_output/flye --threads 2
