#!/bin/bash -l
#SBATCH -A uppmax2024-2-7
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:20:00
#SBATCH -J prokka_001
#SBATCH -e error_prokka
#SBATCH --mail-type=ALL
#SBATCH --mail-user emblap@hotmail.se
#SBATCH --output=prokka.out
#SBATCH --reservation=uppmax2024-2-7_4

# Load modules
module load bioinfo-tools
module load prokka/1.45-5b58020

# Commands
prokka --outdir /home/embla/Genome-analysis-proj2/analysis_output/prokka --prefix mygenome /home/embla/Genome-analysis-proj2/analysis_output/bwa_pilon/bwa_pilon.fasta
