#!/bin/bash -l
#SBATCH -A uppmax2024-2-7
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:10:00
#SBATCH -J blast_001
#SBATCH -e error_blast
#SBATCH --mail-type=ALL
#SBATCH --mail-user emblap@hotmail.se
#SBATCH --output=blast.out

# Load modules
module load bioinfo-tools
module load blast/2.15.0+

# Commands
makeblastdb -in /home/embla/Genome-analysis-proj2/analysis_output/bwa_pilon/bwa_pilon.fasta -dbtype nucl -out fasta_db
blastn -query /home/embla/Genome-analysis-proj2/rawdata/2_Beganovic_2023/reference_genome/HP126_genome.fasta -db fasta_db -out /home/embla/Genome-analysis-proj2/analysis_output/blast/blast_001.txt -outfmt 6
